---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bitwarden-access-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgCbYLDSiOBzKspTRsRpVPJcHGW56lXuZAXwf6+QxgUNcqflzsOnCzgfv5WnAoQlXSUvOhcz2nf2rlFNvlv+DJlcxh2CpUbTAbEgTo40J5+f8zgillsFvgXmtmVDrkQ4FVA89pQxETfgS++BsBPpWoJZnBwGSrTgHeQ3TxZfL+/Hco/dpWnOHGixRIjlmA+FCFqTCvX/OT6NGfPx0Tqh/+ytlWuWuyuWhWfqry1BQ0TYCcOlW08D+5iwqM1RAHKrFw6HQJBTpxSlazxdP6E8XcAsfNSrs9m8RhpSE6nEQ3u+Ca/9e4QAWPKbFfrhsRuyU78a6hWbeeX+kmi0EE+egQN+QrVE/QdzoLSy+EAE1o6M8CWtaxOQP6VvSJRhxDfbdO79V8plujFiRu6FQKn/Qd4DT1sgkhELyw03C4AI/WmW0L+rHYTy7aWiPwgwi9BAkFKIyf93KkygJRv+/LOniIg4iEOj1T0zFIQnHZ6Qa/JongcebAAGRvBEIWI5JlfclOTE8g7YM9B2hvD6ZmLNoiJtyX0Kj4fw2iBtlqEK8CDLnp9Q4Kyo0Nv76qr+75dhozXKAuD4nzvYtjTNuHkx03hIxB/Vmf/OZBd041dD1R4kz3FUVJyQaIG5GaYIN2aXIi6jWNk+fdl8bMrJd2EowMunEBy45jm8m0d+MoBHaJu3+/X3gHba6pghSawwcG7drhkRHkyPz8t3TYoBY+gkAcU/kiidY5a2lGIeHguvFm4DLOcF9uC+/7kSkJDOpfqBjQEmX75DhtGSoE0ltbKizScCnyjgf4NgKIHLxKyBtKxiakTmSP59HWoHfGk5jnkh
  template:
    metadata:
      creationTimestamp: null
      name: bitwarden-access-token
      namespace: external-secrets
