apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-bongima-dnszone
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  acme:
    email: joelbong@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-bongima-dnszone
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
        - bongima.be
