apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-bongima-subdomains
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  secretName: cloudflare-bongima-subdomains
  issuerRef:
    name: cloudflare-bongima-dnszone
  dnsNames:
  - "*.bongima.be"