crds:
  keep: false

configs:
  cm:
    exec.enabled: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    application.resourceTrackingMethod: annotation+label
    installationID: management-cluster
    statusbadge.enabled: true
  params:
    server.insecure: true

dex:
  enabled: false

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2