apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/joelbong/infra-code.git
      revision: HEAD
      files:
        - path: clusters/**/helm-addons/*.helm-config.yaml
      values:
        cluster: "{{ index .path.segments 1 }}" 
        namespace: "{{ index .path.segments 2 }}"
        addon: '{{ .path.filenameNormalized | replace ".helm-config.yaml" "" }}'
  template:
    metadata:
      name: "{{ .values.addon }}-{{.values.namespace }}-{{ .values.cluster }}"
    spec:
      project: admin
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: "{{ .podSecurityLevel }}"
        automated:
          prune: true
          selfHeal: true    
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - PruneLast=true
        - ServerSideApply=true
        - FailOnSharedResource=true
      source:
        repoURL: "{{ .repository }}"
        chart: "{{ .chart }}"
        targetRevision: "{{ .version }}"
        helm:
          valueFiles:
          - "{{ .values.addon }}.helm-values.yaml"
          ignoreMissingValueFiles: true
      destination:
        server: "{{ .values.cluster }}"
        namespace: "{{ .values.namespace }}"