crds:
  keep: false

configs:
  cm:
    exec.enabled: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    application.resourceTrackingMethod: annotation+label
    installationID: management-cluster
    statusbadge.enabled: true
  params:
    server.insecure: true
    controller.status.processors: 3
    controller.operation.processors: 3

dex:
  enabled: false

redis-ha:
  enabled: true
  persistentVolume:
    enabled: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicas: 2