apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: password
    remoteRef:
      key: pihole-admin