#https://cluster-api-operator.sigs.k8s.io/
#https://cluster-api.sigs.k8s.io/introduction
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: v1.9.5
