apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxmox-variables
type: Opaque
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    template:
        data:
          ## -- Controller settings -- ##
          PROXMOX_URL: "https://pve2.bongima.be:8006"
          PROXMOX_TOKEN: "capmox@pve!capi"
          PROXMOX_SECRET: "{{ .secret }}"
          ## -- Required workload cluster default settings -- ##
          PROXMOX_SOURCENODE: "pve2"
          TEMPLATE_VMID: "7000"   
          ALLOWED_NODES: "[pve2]" 
          VM_SSH_KEYS: ""
          ## -- Required workload cluster default settings -- ##
          CONTROL_PLANE_ENDPOINT_IP: "10.6.110.50"
          NODE_IP_RANGES: "[10.6.110.50-10.6.110.70]"
  data:
  - secretKey: secret
    remoteRef:
      key: proxmox-capi-access-token