apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxmox-variables
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          platform.ionos.com/secret-type: "proxmox-credentials"
      data:
        PROXMOX_URL: "https://pve2.bongima.be:8006"
        PROXMOX_TOKEN: "capmox@pve!capi"
        PROXMOX_SECRET: "{{ .secret }}"
  data:
    - secretKey: secret
      remoteRef:
        key: proxmox-capi-access-token
