#https://github.com/ionos-cloud/cluster-api-provider-proxmox/tree/main
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: proxmox
spec:
  version: v0.7.1
  configSecret:
    name: proxmox-credentials
