apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster
  labels:
    cluster.x-k8s.io/cluster-name: cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  infrastructureRef:
    kind: ProxmoxCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: proxmox-cluster
  controlPlaneRef:
    kind: TalosControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: talos-control-planes
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: proxmox-cluster
spec:
  controlPlaneEndpoint:
    host: 10.6.110.50
    port: 6443
  ipv4Config:
    addresses:
      - 10.6.110.50-59
  allowedNodes: [pve2]
  credentialsRef:
    name: proxmox-credentials
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-control-planes
spec:
  version: 32.3
  replicas: 1
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: control-plane-machine-template
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.9.4
      strategicPatches:
        - |
          machine:
            install:
              image: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.9.4
        - |
          cluster:
            network:
              cni:
                name: custom
                urls:
                  - https://raw.githubusercontent.com/joelbong/infra-code/refs/heads/main/management-cluster/cilium/helm-output.yaml
            proxy:
              disabled: true
        - |
          cluster:
            externalCloudProvider:
              enabled: true
              manifests:
                - https://raw.githubusercontent.com/sergelogvinov/proxmox-cloud-controller-manager/refs/tags/v0.7.0/docs/deploy/cloud-controller-manager.yml
                - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/refs/tags/v0.11.0/docs/deploy/proxmox-csi-plugin.yml
                - https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        - |
          cluster:
            inlineManifests:
              - name: create-storage-class
                contents: |
                  ---
                  apiVersion: storage.k8s.io/v1
                  kind: StorageClass
                  metadata:
                    name: proxmox-csi
                    annotations:
                      storageclass.kubernetes.io/is-default-class: "true"
                  allowVolumeExpansion: true
                  parameters:
                    csi.storage.k8s.io/fstype: ext4
                    storage: kubernetes-pv
                    cache: none
                    ssd: "true"
                  mountOptions:
                    - noatime
                  provisioner: csi.proxmox.sinextra.dev
                  reclaimPolicy: Delete
                  volumeBindingMode: WaitForFirstConsumer
              - name: metallb-ippool
                contents: |
                  ---
                  apiVersion: metallb.io/v1beta1
                  kind: L2Advertisement
                  metadata:
                    name: l2-advertisement
                    namespace: metallb-system
                  ---
                  apiVersion: metallb.io/v1beta1
                  kind: IPAddressPool
                  metadata:
                    name: ip-pool
                    namespace: metallb-system
                  spec:
                    addresses:
                    - 10.6.110.60-10.6.110.70
---
kind: ProxmoxMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: control-plane-machine-template
spec:
  template:
    spec:
      checks:
        skipCloudInitStatus: true
        skipQemuGuestAgent: true
      sourceNode: pve2
      templateID: 7000
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: worker-nodes
spec:
  clusterName: cluster
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: cluster
    spec:
      metadata:
        labels:
          cluster.x-k8s.io/cluster-name: cluster
      clusterName: cluster
      version: 32.3
      bootstrap:
        configRef:
          kind: TalosConfigTemplate
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          name: talos-worker-bootstrap
      infrastructureRef:
        kind: ProxmoxMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        name: worker-machine-template
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talos-worker-bootstrap
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.9.4
      strategicPatches:
        - |
          machine:
            install:
              image: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.9.4
        - |
          cluster:
            network:
              cni:
                name: custom
                urls:
                  - https://raw.githubusercontent.com/joelbong/infra-code/refs/heads/main/management-cluster/cilium/helm-output.yaml
            proxy:
              disabled: true
        - |
          cluster:
            externalCloudProvider:
              enabled: true
              manifests:
                - https://raw.githubusercontent.com/sergelogvinov/proxmox-cloud-controller-manager/refs/tags/v0.7.0/docs/deploy/cloud-controller-manager.yml
                - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/refs/tags/v0.11.0/docs/deploy/proxmox-csi-plugin.yml
                - https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        - |
          cluster:
            inlineManifests:
              - name: create-storage-class
                contents: |
                  ---
                  apiVersion: storage.k8s.io/v1
                  kind: StorageClass
                  metadata:
                    name: proxmox-csi
                    annotations:
                      storageclass.kubernetes.io/is-default-class: "true"
                  allowVolumeExpansion: true
                  parameters:
                    csi.storage.k8s.io/fstype: ext4
                    storage: kubernetes-pv
                    cache: none
                    ssd: "true"
                  mountOptions:
                    - noatime
                  provisioner: csi.proxmox.sinextra.dev
                  reclaimPolicy: Delete
                  volumeBindingMode: WaitForFirstConsumer
              - name: metallb-ippool
                contents: |
                  ---
                  apiVersion: metallb.io/v1beta1
                  kind: L2Advertisement
                  metadata:
                    name: l2-advertisement
                    namespace: metallb-system
                  ---
                  apiVersion: metallb.io/v1beta1
                  kind: IPAddressPool
                  metadata:
                    name: ip-pool
                    namespace: metallb-system
                  spec:
                    addresses:
                    - 10.6.110.60-10.6.110.70
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: worker-machine-template
spec:
  template:
    spec:
      checks:
        skipCloudInitStatus: true
        skipQemuGuestAgent: true
      sourceNode: pve2
      templateID: 7000
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cluster-secrets
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: cluster
  resources:
    - name: cilium-ca
      kind: Secret
      namespace: kube-system
    - name: hubble-server-certs
      kind: Secret
      namespace: kube-system
    - name: proxmox-cloud-controller-manager
      kind: Secret
      namespace: kube-system
    - name: proxmox-csi-plugin
      kind: Secret
      namespace: csi-proxmox
