#https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
repository: https://bitnami-labs.github.io/sealed-secrets
name: sealed-secrets
version: 2.17.1
valuesPath: sealed-secrets.helm-values.yaml
updateVersion: 1.0.0