apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-bongima-subdomains
spec:
  secretName: cloudflare-bongima-subdomains
  issuerRef:
    name: cloudflare-bongima-dnszone
  dnsNames:
  - argocd.bongima.be