apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: kubernetes-pv
  cache: none
  ssd: "true"
mountOptions:
  - noatime
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer