apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/joelbong/infra-code.git
      revision: main
      files:
        - path: clusters/*/*/helm/*/config.yaml
      values:
        cluster: "{{ index .path.segments 1 }}" 
        namespace: "{{ index .path.segments 2 }}"
        addon: "{{ index .path.segments 4 }}"
  template:
    metadata:
      name: "helm-{{ .values.addon }}-{{.values.namespace }}-{{ .values.cluster }}"
    spec:
      project: admin
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: "{{ .podSecurityLevel }}"
          annotations: {}
        automated:
          prune: true
          selfHeal: true    
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - PruneLast=true
        - ServerSideApply=true
        - FailOnSharedResource=true
      sources:
        - repoURL: "{{ .repository }}"
          chart: "{{ .chart }}"
          targetRevision: "{{ .version }}"
          helm:
            releaseName: "{{ .values.addon }}"
            valueFiles:
              - "$values/{{.path.path}}/values.yaml"
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/joelbong/infra-code.git
          targetRevision: main
          ref: values
      destination:
        name: "{{ .values.cluster }}"
        namespace: "{{ .values.namespace }}"