apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/joelbong/infra-code.git
      revision: HEAD
      directories:
        - path: clusters/*/*/resources
      values:
        cluster: "{{ index .path.segments 1 }}" 
        namespace: "{{ index .path.segments 2 }}"
  template:
    metadata:
      name: "resources-{{.values.namespace }}-{{ .values.cluster }}"
    spec:
      project: admin
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true    
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - PruneLast=true
        - ServerSideApply=true
        - FailOnSharedResource=true
      source:
        repoURL: https://github.com/joelbong/infra-code.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        name: "{{ .values.cluster }}"
        namespace: "{{ .values.namespace }}"