---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bitwarden-access-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgA+co8ojyGqzhV6oNEs2hDgKzeFtrEwc6nPfRvOJrQDuAWlUXNC9g/L3bYFMkOE9rsO3j60ZDbW371xUg+MbB2WWx98aYgIRLitrN8ITF6kN8IEcnvzomC2r6fZN5G9QY/WPxe8SbuORF/oIGsEfEQxp90bEOswzneZokhqJyXy9A/lU7hGOtLApl3PzAZ4WlBI+V5HF626sgfYNwxr6yJz5C6+xsABgx3dh49hNRXo0/X2yWKFlp/jSSJv8GhrewHrcLfxWN/EyW7/uxevEim1qXRvUENqe1PjRa3hUBbVsIYd73dlw7wikxBPNjk4C43MscvRxMaxm/pqOiL2a8mz+ch4WX0R+npihJ26tnlK5O9iwIKlflRHkMtY3UlJxqtumvJ+PhfQSosocK4rPF+LSWAxSVPHW+x9xhtcbcHzsX3/sdrxukfupjSPPkJfEIJNOXpNlWPWdlsUCHSGI+GAlEwQ16Dd6F+xk2TebsqKlpxusnNHys10Vjkh/xBQMo6DH0N7m/ZjqW6HSu28cae1XNcxeL08SgNsEUMO5/m+RX1DJVPjYZ0yoKIJRSTKhiLiWyUrFkd3Jo5UCWuLQ1STjBBwNn+8fwj2QxNqUGdoO84lYtlQWL8kaKf8oWBWH4RdQ4daHnKPE2DmPYPj4K6VG06McTDFhR4hTH48EBWSskjo388EOM0nDRQ/4nHcD8JgrHKvMrWju6U5StZIVOMPSIpLSSjkWhILz8f72D2JFtZw21XxrQoHQO8tXWy5qLpf/c//dzS9UE5nCmT2064tvyS3q99EfQOtdKQkoHQfEAhKuQfvxzmoeH5fHnKq
  template:
    metadata:
      creationTimestamp: null
      name: bitwarden-access-token
      namespace: external-secrets
