#https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
repository: https://charts.external-secrets.io
name: external-secrets
version: 0.13.0
valuesPath: external-secret.helm-values.yaml
updateVersion: 1.0.0