#With traefik https://github.com/kubernetes-sigs/external-dns/pull/3055
sources:
  - service
  - traefik-proxy
provider:
  name: pihole
registry: noop
extraArgs:
  - "--traefik-disable-legacy"
image:
  #temporary because the chart has not yet updated the app to latest version
  #in this version support for Pihole v6 is added
  tag: v0.17.0
env:
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    value: http://pihole.bongima.be:8080
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole
        key: password
        optional: true
  - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    value: "6"
