apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repository-credential
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
        data:
          type: git
          url: git@github.com:joelbong/infra-code.git
          sshPrivateKey: "{{ .privatekey | toString }}"
  data:
  - secretKey: privatekey
    remoteRef:
      key: github-private-key