existingConfigSecret: proxmox-ccm-access-token

enabledControllers:
  - cloud-node
  - cloud-node-lifecycle

logVerbosityLevel: 4

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule