apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - PruneLast=true
    - ServerSideApply=true
    - FailOnSharedResource=true
  source:
    repoURL: https://github.com/joelbong/infra-code.git
    targetRevision: HEAD
    path: argocd/application-sets
  destination:
    name: in-cluster
    namespace: argocd