app:
  name: dumbkan
image:
  registry: docker.io
  repository: dumbwareio/dumbkan
  tag: latest
  digest: ""
service:
  ports:
    http:
      name: http
      port: 80
      targetPort: 3000
fullnameOverride: dumbkan
persistence:
  enabled: true
  mountPath: /app/data
  size: 1Gi
