#https://artifacthub.io/packages/helm/cert-manager/cert-manager
repository: https://charts.jetstack.io
name: cert-manager
version: 1.16.3
valuesPath: cert-manager.helm-values.yaml
updateVersion: 1.0.0