apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argus-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    template:
      data:
        config.yaml: |
          defaults:
            service:
              options:
                interval: 5h
              latest_version:
                access_token: "{{ .github_access_token }}"
          notify:
            slack:
              type: slack
              url_fields:
                Token: "{{ .slack_bot_token_halpi }}"
                Channel: homelab-updates
          service:
            opnsense/core:
              latest_version:
                type: url
                url: https://github.com/opnsense/core/tags
                url_commands:
                  - type: regex
                    regex: '\/releases\/tag\/([0-9.]+)\"'
              deployed_version:
                url: https://opnsense.bongima.be/api/core/firmware/status
                basic_auth:
                  username: "A+1HoI05TZb1VMJYmopD3ymLHTu/1pBzA9OZR0Kl2OcA1UpejXECE7NxIdUXvoHLp7J+8BLNnqjZdykB"
                  password: "{{ .opensense_password }}"
                json: product.product_version
                regex: '([0-9.]+)'
              dashboard:
                web_url: https://docs.opnsense.org/CE_releases.html
                icon: https://github.com/opnsense/core/raw/master/src/opnsense/www/themes/opnsense/build/images/icon-logo.svg
            argoproj/argo-cd:
              latest_version:
                type: github
                url: argoproj/argo-cd
                url_commands:
                - type: regex
                  regex: 'v([0-9.]+)$'
              deployed_version:
                url: https://argocd.bongima.be/api/version
                json: Version
                regex: v([0-9.]+)
              dashboard:
                web_url: 'https://github.com/argoproj/argo-cd/releases/v{{"{{"}} version {{"}}"}}'
                icon: https://avatars.githubusercontent.com/u/30269780?s=200&v=4
            pihole-core:
              latest_version:
                type: github
                url: https://github.com/pi-hole/pi-hole
              options:
                semantic_versioning: true
              deployed_version:
                type: manual
                version: 6.1.2
              dashboard:
                web_url: https://github.com/pi-hole/pi-hole/releases
                icon: https://pi-hole.net/wp-content/uploads/2016/12/cropped-Vortex-R-192x192.png

  data:
    - secretKey: github_access_token
      remoteRef:
        key: github-access-token
    - secretKey: slack_bot_token_halpi
      remoteRef:
        key: slack-bot-token-halpi
    - secretKey: opensense_password
      remoteRef:
        key: opensense-password
